---
- name: Query defined programs in CICS

  #hosts: "localhost"
  hosts: localhost
  gather_facts: false

  vars:
    attributes:
      - eyu_cicsname
      - release
      - jobid
      - totltasks

  tasks:
    # Install module dependencies
    - name: Make sure CMCI module dependencies are installed
      ansible.builtin.pip:
        name:
          - requests
          - xmltodict
          - typing;python_version<"3.5"

    - name: Retrieve PROGRAM resources
      ibm.ibm_zos_cics.cmci_get:
        cmci_host: "{{ cmci_host }}"
        cmci_port: "{{ cmci_port }}"
        cmci_user: "{{ cmci_user | default(omit) }}"
        cmci_password: "{{ cmci_password | default(omit) }}"
        scheme: "{{ cmci_scheme }}"
        insecure: true          # remove if using trusted certificates

        context: "{{ cmci_context }}"
        type: CICSProgram

        resources:
          filter:
            program: "MDG*"

      register: result

    - name: Display program name list
      debug:
        var: program_names
      vars:
        program_names: "{{ result.records | map(attribute='program') | list }}"