---
- name: Query defined programs in CICS

  #hosts: "localhost"
  hosts: localhost
  gather_facts: false

  vars:
    attributes:
      - eyu_cicsname
      - release
      - jobid
      - totltasks

  tasks:
    # Install module dependencies
    - name: Make sure CMCI module dependencies are installed
      ansible.builtin.pip:
        name:
          - requests
          - xmltodict
          - typing;python_version<"3.5"

    - name: Retrieve PROGRAM resources
      ibm.ibm_zos_cics.cmci_get:
        cmci_host: "{{ cmci_host }}"
        cmci_port: "{{ cmci_port }}"
        cmci_user: "{{ cmci_user | default(omit) }}"
        cmci_password: "{{ cmci_password | default(omit) }}"
        scheme: "{{ cmci_scheme }}"
        insecure: true          # remove if using trusted certificates

        context: "{{ cmci_context }}"
        type: CICSProgram

        resources:
          filter:
            program: "MDG*"

      register: result

    - name: Display program name list
      debug:
        var: program_names
      vars:
        program_names: "{{ result.records | map(attribute='program') | list }}"

    - name: Generate CICS Prometheus metrics
      ansible.builtin.copy:
        dest: "{{ cics_metrics_path }}"
        mode: "0600"
        vars:
          program_names: "{{ result.records | map(attribute='program') | list }}"
        content: |
          # HELP cics_program_info Static information about CICS programs
          # TYPE cics_program_info gauge
          {% for program in program_names %}
          cics_program_info{program="{{ program }}"} 1
          {% endfor %}

          # HELP cics_program_total Number of CICS programs
          # TYPE cics_program_total gauge
          cics_program_total {{ program_names | length }}